In [1]:
import pandas as pd

In [28]:
pd.read_csv("http://www.football-data.co.uk/mmz4281/1819/E0.csv").head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,10/08/18,Man United,Leicester,2,1,H,1,0,H,...,1.79,17,-0.75,1.75,1.70,2.29,2.21,1.55,4.07,7.69
1,E0,11/08/18,Bournemouth,Cardiff,2,0,H,1,0,H,...,1.83,20,-0.75,2.20,2.13,1.80,1.75,1.88,3.61,4.70
2,E0,11/08/18,Fulham,Crystal Palace,0,2,A,0,1,A,...,1.87,22,-0.25,2.18,2.11,1.81,1.77,2.62,3.38,2.90
3,E0,11/08/18,Huddersfield,Chelsea,0,3,A,0,2,A,...,1.84,23,1.00,1.84,1.80,2.13,2.06,7.24,3.95,1.58
4,E0,11/08/18,Newcastle,Tottenham,1,2,A,1,2,A,...,1.81,20,0.25,2.20,2.12,1.80,1.76,4.74,3.53,1.89

In [75]:
def get_data():
    eng = pd.read_csv(URL + "EC.csv")
    fra = pd.read_csv(URL + "F1.csv")
    ger = pd.read_csv(URL + "D1.csv")
    ita = pd.read_csv(URL + "I1.csv")
    spa = pd.read_csv(URL + "SP1.csv")
    fixtures = pd.read_csv("http://www.football-data.co.uk/fixtures.csv")
    return eng, fra, ger, ita, spa, fixtures

In [76]:
def get_fixtures(fixtures):
    cols = ['Div', 'Date', 'HomeTeam', 'AwayTeam', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
           'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
           'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA',
           'BbAvAHA']
    eng_fixs = fixtures[fixtures["Div"] == "EC"][cols]
    fra_fixs = fixtures[fixtures["Div"] == "F1"][cols]
    ger_fixs = fixtures[fixtures["Div"] == "D1"][cols]
    ita_fixs = fixtures[fixtures["Div"] == "I1"][cols]
    spa_fixs = fixtures[fixtures["Div"] == "SP1"][cols]
    return eng_fixs, fra_fixs, ger_fixs, ita_fixs, spa_fixs

In [77]:
def get_new_matches():
    URL = "http://www.football-data.co.uk/mmz4281/1819/"
    eng, fra, ger, ita, spa, fixtures = get_data()
    eng_fixs, fra_fixs, ger_fixs, ita_fixs, spa_fixs = get_fixtures(fixtures)
    eng = pd.concat([eng, eng_fixs]).reset_index(drop=True)
    fra = pd.concat([fra, fra_fixs]).reset_index(drop=True)
    ger = pd.concat([ger, ger_fixs]).reset_index(drop=True)
    ita = pd.concat([ita, ita_fixs]).reset_index(drop=True)
    spa = pd.concat([spa, spa_fixs]).reset_index(drop=True)
    return eng, fra, ger, ita, spa, fixtures

In [78]:
eng, fra, ger, ita, spa, fixtures = get_new_matches()